gazebo_ros_control/pid_gains:
  left_wheel_hinge_front: {p: 1.0, i: 0.0, d: 1.0}
  right_wheel_hinge_front: {p: 1.0, i: 0.0, d: 1.0}
  left_wheel_hinge_mid: {p: 1.0, i: 0.0, d: 1.0}
  right_wheel_hinge_mid: {p: 1.0, i: 0.0, d: 1.0}
  left_wheel_hinge_back: {p: 1.0, i: 0.0, d: 1.0}
  right_wheel_hinge_back: {p: 1.0, i: 0.0, d: 1.0}
